on:
  push:
    tags:
      - 'v*'

name: Publish

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: generate-changelog
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_PUBLISH_TOKEN}
          yarn install --immutable
          yarn build
          npm publish
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release Notes
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              generate_release_notes: true
            });